### ISSUE TITLE
Project was already existing.

### ISSUE THREAD

**Issue by miermontoto** [lordmulder/cecho#1]
already existing [here](https://www.codeproject.com/Articles/17033/Add-Colors-to-Batch-Files)

**Comment by lordmulder** [comment]
That's a completely different project. My code is **not** related to that project at all.

**Comment by miermontoto** [comment]
it is a different project but the same idea. no point on doing the same. it even uses similar syntax (\n)

**Comment by lordmulder** [comment]
Ever heard about **_„the route is the goal“_** :smirk_cat:

Also while the idea is similar, the implementation is not. Their program is about ~5 times the size of mine!

They have more features though. People can choose what they prefer.

(BTW: Tell the KDE guys that there is no sense in their project, because there's GNOME already... :stuck_out_tongue:)

**Comment by miermontoto** [comment]
I don't know any of those people. Your project is working almost exactly as that one. I know that it is fun to code but copying ideas seems like a bad move.

Also, the size doesn't matter at all. You know, nobody is going to die for 26kb...

EDIT: read [this](https://www.codeproject.com/Messages/2171669/Re-slightly-smaller-embedded-code.aspx)

**Comment by lordmulder** [comment]
What are you complaining here ??? :unamused:

I could just have kept my work to myself. Instead I decided to share it with the community, under an OpenSource license, in the hope that it might be useful for others too. You should either show some gratitude (or at least respect other peoples efforts) - or just _**ignore**_ software that isn't helpful for you. It's **not** like that I asked you to use my software. So what exactly do you expect to achieve by that?

Also, to make it very clear: I did **NOT** copy anything! I wrote the code 100% by myself, from the scratch. I did **NOT** even know about the program by Thomas Polaert by that time! Anyway, the idea of colored console output is _**decades**_ old. The "echo" command on Unix and Unix-like systems (e.g.. Linux) has supported this since ages. It's a well-known shortcoming of the Windows command-line interpreter ("cmd.exe") that you can't set color via the built-in `echo` command. It just seems natural to create an "enhanced" `echo` tool with color support for Windows. There are, without any doubt, a multitude of similar tools out there...

(BTW: Took me ~30 seconds to bring up [***colorecho***](http://wp.xin.at/archives/3064) on Google, yet another alternative for colored echo'ing)

-------

> EDIT: read this

Just for the notes: I did **not** "compress" my program to make it appear smaller. It's only 6 KB in size, because it was written by using the Win32 API directly, rather than linking against the Visual C++ runtime libs.

**Comment by miermontoto** [comment]
it took 30 seconds to find another project but it was just too difficult to search **YOUR PROJECT'S NAME** on Google too see if it was a duplicate.

"Instead I decided to share it with the community" - it doesn't help because there was already another project doing this.

"You should either show some gratitude" - I already showed my gratitude to the original project.

"or just ignore software that isn't helpful for you" - thank you for the piece of advice

EDIT: bye

**Comment by lordmulder** [comment]
> it took 30 seconds to find another project but it was just too difficult to search YOUR PROJECT'S NAME on Google too see if it was a duplicate.

I don't even waste any time trying to understand what you are trying to tell us with that sentence.

&nbsp;

> "Instead I decided to share it with the community" - it doesn't help because there was already another project doing this.

**_“Dear Mr. Linus Torvalds, I hate to tell you, but that 'Linux' operating system you have created is completely pointless, because the 'Unix' operating system, which does "the same thing", existed before.”_**

**`</sarcasm>`**

:laughing:

&nbsp;

> EDIT: bye

Bye, bye, Mr. Troll! 

:lock:
