### ISSUE TITLE
Redone in C#

### ISSUE THREAD

**Issue by pandasoli** [lordmulder/cecho#2]
I made my version of this lib in C#.
I didn't do it based on your code, but on how it works. I think the way it works is very interesting.

I just couldn't reproduce the way it identifies the color names inside the "{}", so I ended up leaving without that functionality.

Are you interested in sailing?

Note: I loved your lib, I use it a lot in my small personal projects with BatchScript.

**Comment by lordmulder** [comment]
Hello,

I'm not quite sure what you mean with "lib" since this is a simple CLI tool with **no** *library* abstraction/interface.

So I'm not surprised that "porting" this to C# actually means a complete re-write.

Also I have no idea what you are referring to here:
> just couldn't reproduce the way it identifies the color names inside the "{}"
> so I ended up leaving without that functionality.

Color names are simply passed as command-line arguments. And that's pretty much all "functionality" that is there 😆 

Best regards.
